"""initial tables

Revision ID: db45559cbb4e
Revises: 
Create Date: 2026-03-23 12:11:37.824213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db45559cbb4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antigen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('gene_name', sa.String(length=100), nullable=True),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_antigen_name_ft', 'antigen', ['name'], unique=False, mariadb_prefix='FULLTEXT')
    op.create_table('linker',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cleavable', sa.Boolean(), nullable=False),
    sa.Column('cleavage_mechanism', sa.String(length=100), nullable=True),
    sa.Column('coupling_chemistry', sa.String(length=100), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.String(length=27), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.Column('iupac_name', sa.Text(), nullable=True),
    sa.Column('mol_weight', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('morgan_fp', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inchikey'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_linker_name_ft', 'linker', ['name'], unique=False, mariadb_prefix='FULLTEXT')
    op.create_table('payload',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('moa', sa.String(length=255), nullable=True),
    sa.Column('bystander_effect', sa.Boolean(), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.String(length=27), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.Column('iupac_name', sa.Text(), nullable=True),
    sa.Column('mol_weight', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('morgan_fp', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inchikey'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_payload_name_ft', 'payload', ['name'], unique=False, mariadb_prefix='FULLTEXT')
    op.create_table('antibody',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('isotype', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('antigen_id', sa.String(length=36), nullable=False),
    sa.Column('heavy_chain_seq', sa.Text(), nullable=True),
    sa.Column('light_chain_seq', sa.Text(), nullable=True),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['antigen_id'], ['antigen.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_antibody_name_ft', 'antibody', ['name'], unique=False, mariadb_prefix='FULLTEXT')
    op.create_table('adc',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dar', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conjugation_site', sa.String(length=30), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('antibody_id', sa.String(length=36), nullable=False),
    sa.Column('linker_id', sa.String(length=36), nullable=False),
    sa.Column('payload_id', sa.String(length=36), nullable=False),
    sa.Column('linker_payload_smiles', sa.Text(), nullable=True),
    sa.Column('structure_3d_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibody.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linker_id'], ['linker.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payload_id'], ['payload.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_adc_name_ft', 'adc', ['name'], unique=False, mariadb_prefix='FULLTEXT')
    op.create_index('ix_adc_status', 'adc', ['status'], unique=False)
    op.create_table('adc_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('adc_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('nct_number', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('orr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tgi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ic50_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ic50_unit', sa.String(length=10), nullable=True),
    sa.Column('cell_line', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adc_id'], ['adc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adc_activity_adc_id'), 'adc_activity', ['adc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adc_activity_adc_id'), table_name='adc_activity')
    op.drop_table('adc_activity')
    op.drop_index('ix_adc_status', table_name='adc')
    op.drop_index('ix_adc_name_ft', table_name='adc', mariadb_prefix='FULLTEXT')
    op.drop_table('adc')
    op.drop_index('ix_antibody_name_ft', table_name='antibody', mariadb_prefix='FULLTEXT')
    op.drop_table('antibody')
    op.drop_index('ix_payload_name_ft', table_name='payload', mariadb_prefix='FULLTEXT')
    op.drop_table('payload')
    op.drop_index('ix_linker_name_ft', table_name='linker', mariadb_prefix='FULLTEXT')
    op.drop_table('linker')
    op.drop_index('ix_antigen_name_ft', table_name='antigen', mariadb_prefix='FULLTEXT')
    op.drop_table('antigen')
    # ### end Alembic commands ###
